<?php
namespace App\Repositories\Orders;
use App\Events\Order\OrderCreateEvent;
use App\Repositories\BaseRepository;
use App\Repositories\Users\User;
use Illuminate\Support\Facades\Auth;

class OrderRepository extends BaseRepository
{
    protected $model;
    private $orderDetailRepository ;
    public function __construct(Order $orders, OrderDetailRepository $orderDetailRepository)
    {
        $this->model = $orders;
        $this->orderDetailRepository = $orderDetailRepository;
    }
    public function create(array $request)
    {
        $data = $request;
        $user = Auth::guard('api')->user();

        $data['user_id'] = $user['id'];

        $order = parent::create($data);
        if($order)
        {
          event(new OrderCreateEvent($order, $request));
        }
        return $order;

    }
    public function delete($id):bool
    {
        $order = $this->getModel()->with(['orderDetails'])->find($id);
        $orderDetailIds = [];
        if(count($order->orderDetails) > 0)
        {
            foreach ($order->orderDetails as $orderDetail)
            {
                $orderDetailIds[] = $orderDetail->id;
            }
             $this->orderDetailRepository->delete($orderDetailIds);

        }
       return parent::delete($id);// TODO: Change the autogenerated stub
    }
}
