<?php
namespace App\Repositories\Orders;
use App\Events\Order\OrderCreated;
use App\Repositories\BaseRepository;
use App\Repositories\Users\User;
use Carbon\Carbon;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;

class OrderRepository extends BaseRepository
{
    protected $model;
    public function __construct(Order $orders)
    {
        $this->model = $orders;
    }
    public function create(array $data)
    {
        $user = Auth::guard('api')->user();

        $data['user_id'] = $user['id'];

        $order = parent::create($data);
        if($order)
        {
          event(new OrderCreated($order, $data));
        }
        return $order;

    }
    public function delete($id)
    {
        parent::delete($id); // TODO: Change the autogenerated stub
        OrderDetail::where('order_id', $id)->delete();
    }

    public function order($id)
    {
        $user = User::query()->where('id', $id)->with(['orders'])->first();
        return $user->orders;

    }


}
